version: '3.8'
services:
  api:
    build: .
    ports:
      - "4000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_HOST=localhost
      - DATABASE_USER=root
      - DATABASE_PASS=password
      - DATABASE_PORT=3306
      - DATABASE_NAME=hirelens_db
      - DATABASE_DIALECT=mysql
    volumes:
      - ./:/app
      - /app/node_modules